const FORM_PROJECT = 'FORM_PROJECT'
const OBTAIN_PROJECTS = 'OBTAIN_PROJECTS'
const ADD_PROJECT = 'ADD_PROJECT'
const VALIDATE_FORM = 'VALIDATE_FORM'
const ACTUAL_PROJECT = 'ACTUAL_PROJECT'
const DELETE_PROJECT = 'DELETE_PROJECT'

const PROJECTS_TASKS = 'PROJECTS_TASKS'
const ADD_TASK = 'ADD_TASK'

const VALIDATE_TASK = 'VALIDATE_TASK'
const DELETE_TASK = 'DELETE_TASK'
const TASK_STATE = 'TASK_STATE'
const ACTUAL_TASK = 'ACTUAL_TASK'
const UPDATE_TASK = 'UPDATE_TASK'

const SHOW_ALERT = 'SHOW_ALERT'
const HIDE_ALERT = 'HIDE_ALERT'

const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
const REGISTER_ERROR = 'REGISTER_ERROR'
const GET_USER = 'GET_USER'
const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
const LOGIN_ERROR = 'LOGIN_ERROR'
const LOGOUT = 'LOGOUT'

export {
    FORM_PROJECT
    , OBTAIN_PROJECTS
    , ADD_PROJECT
    , VALIDATE_FORM
    , ACTUAL_PROJECT
    , DELETE_PROJECT
    , PROJECTS_TASKS
    , ADD_TASK

    , VALIDATE_TASK
    , DELETE_TASK
    , TASK_STATE
    , ACTUAL_TASK
    , UPDATE_TASK
    , SHOW_ALERT
    , HIDE_ALERT
    , REGISTER_SUCCESSFUL
    , REGISTER_ERROR
    , GET_USER
    , LOGIN_SUCCESSFUL
    , LOGIN_ERROR
    , LOGOUT

}

